# Generated by tapster on 2026-03-16T10:26:36.951877Z
class Flit < Formula
  desc "AI-powered Conventional Commits Generator"
  homepage "https://github.com/CalsRanna/auto_commit"
  url "https://github.com/CalsRanna/auto_commit/releases/download/v1.0.11/flit"
  sha256 "1df71097814268cefa73f04c514695f22a25783c14deb6e1ce2d3709140a25c7"
  license "MIT"

  

  def install
    bin.install "flit"
  end

  test do
    system "#{bin}/flit", "--version"
  end
end
