# Generated by tapster on 2025-09-26T02:32:02.998311Z
class Journal < Formula
  desc "Homebrew Package Publishing Automation Tool"
  homepage "https://github.com/CalsRanna/auto_reflect"
  license "MIT"
  version "1.0.0"

  url "https://github.com/CalsRanna/auto_reflect/releases/download/v1.0.0/journal"
  sha256 "e09c6b281b267aad3c7a390c9cbd3f49df56360f1b3906dfd3ffebce4c33329a"

    depends_on "gh"


  def install
    bin.install "journal"
  end

  test do
    system "#{bin}/journal", "--version"
  end
end
