# Generated by tapster on 2025-11-12T14:16:36.467728Z
class Tapster < Formula
  desc "A command-line tool for automating Homebrew package publishing."
  homepage "https://github.com/CalsRanna/auto_homebrew"
  url "https://github.com/CalsRanna/auto_homebrew/releases/download/v1.0.2/tapster"
  sha256 "4beb39e677d3ca4ed035503ac71ad2db4c3f5ee28169485696a57c6bf98efcf8"
  license "MIT"

  depends_on "gh"

  def install
    bin.install "tapster"
  end

  test do
    system "#{bin}/tapster", "--version"
  end
end
