# Generated by tapster on 2025-09-26T03:58:18.644577Z
class Tapster < Formula
  desc "A command-line tool for automating Homebrew package publishing"
  homepage "https://github.com/CalsRanna/auto_homebrew"
  url "https://github.com/CalsRanna/auto_homebrew/releases/download/v1.0.0/tapster"
  sha256 "79f29328aecff393eb35bf2d6955ed249bd4e3b23a74257e4f29447883d8590b"
  license "MIT"

  depends_on "gh"

  def install
    bin.install "tapster"
  end

  test do
    system "#{bin}/tapster", "--version"
  end
end
