# Generated by tapster on 2025-09-26T07:52:32.289950Z
class Tapster < Formula
  desc "A command-line tool for automating Homebrew package publishing."
  homepage "https://github.com/CalsRanna/auto_homebrew"
  url "https://github.com/CalsRanna/auto_homebrew/releases/download/v1.0.1/tapster"
  sha256 "6169749ca895503d58f7afa96a8ac58e2cbfd91f27ba7a8fb36eee13e277f06c"
  license "MIT"

  depends_on "gh"

  def install
    bin.install "tapster"
  end

  test do
    system "#{bin}/tapster", "--version"
  end
end
