# Generated by tapster on 2026-08-13T08:08:34.623122Z
class Bump < Formula
  desc "Semantic version management for Dart and Flutter projects."
  homepage "https://github.com/CalsRanna/auto_version"
  url "https://github.com/CalsRanna/auto_version/releases/download/v1.0.1/bump-macos"
  sha256 "3bb69b3f5be66b1051a3c5b70e64ea53f299cd76dd516b25f4848faccf550a81"
  license "MIT"

  

  def install
    bin.install "bump-macos" => "bump"
  end

  test do
    system "#{bin}/bump", "--version"
  end
end
