# Generated by tapster on 2026-08-13T08:34:12.586102Z
class Bump < Formula
  desc "Semantic version management for Dart and Flutter projects."
  homepage "https://github.com/CalsRanna/auto_version"
  if OS.mac?
    url "https://github.com/CalsRanna/auto_version/releases/download/v1.0.1/bump-macos"
    sha256 "3bb69b3f5be66b1051a3c5b70e64ea53f299cd76dd516b25f4848faccf550a81"
  else
    url "https://github.com/CalsRanna/auto_version/releases/download/v1.0.1/bump-linux"
    sha256 "6828f3b85c2fe708a5088397845ea19b98f1695ab59ba078cfa17846683c185f"
  end

  license "MIT"

  

  def install
    if OS.mac?
      bin.install "bump-macos" => "bump"
    else
      bin.install "bump-linux" => "bump"
    end

  end

  test do
    system "#{bin}/bump", "--version"
  end
end
