# Generated by tapster on 2026-08-13T07:45:43.865806Z
class Flit < Formula
  desc "AI-powered Conventional Commits Generator"
  homepage "https://github.com/CalsRanna/auto_commit"
  url "https://github.com/CalsRanna/auto_commit/releases/download/v1.0.12/flit-macos"
  sha256 "6ea54f1bf502a59a2d5fc4e88c7a251845bd550e86f2cf02dabeb35f9140ba59"
  license "MIT"

  

  def install
    bin.install "flit-macos" => "flit"
  end

  test do
    system "#{bin}/flit", "--version"
  end
end
