# Generated by tapster on 2026-08-13T08:33:56.586926Z
class Flit < Formula
  desc "AI-powered Conventional Commits Generator"
  homepage "https://github.com/CalsRanna/auto_commit"
  if OS.mac?
    url "https://github.com/CalsRanna/auto_commit/releases/download/v1.0.12/flit-macos"
    sha256 "6ea54f1bf502a59a2d5fc4e88c7a251845bd550e86f2cf02dabeb35f9140ba59"
  else
    url "https://github.com/CalsRanna/auto_commit/releases/download/v1.0.12/flit-linux"
    sha256 "8c02b4a04d7711d6c0f922860ff2d963d35aa2f3436d55611512744c099d1ff0"
  end

  license "MIT"

  

  def install
    if OS.mac?
      bin.install "flit-macos" => "flit"
    else
      bin.install "flit-linux" => "flit"
    end

  end

  test do
    system "#{bin}/flit", "--version"
  end
end
