# Generated by tapster on 2026-08-14T08:33:51.027343Z
class Flit < Formula
  desc "AI-powered Conventional Commits Generator"
  homepage "https://github.com/CalsRanna/auto_commit"
  if OS.mac?
    url "https://github.com/CalsRanna/auto_commit/releases/download/v1.0.13/flit-macos"
    sha256 "53c0447e04bb658829346c34f69f103e8126d3ee5a04ee5cb1a336a6fa3059ab"
  else
    url "https://github.com/CalsRanna/auto_commit/releases/download/v1.0.13/flit-linux"
    sha256 "0132d7e3bde7c5f2fcc5af47c105ad11d8002ae1bfdba439344bd7ad9ca1f37a"
  end

  license "MIT"

  

  def install
    if OS.mac?
      bin.install "flit-macos" => "flit"
    else
      bin.install "flit-linux" => "flit"
    end

  end

  test do
    system "#{bin}/flit", "--version"
  end
end
