# Generated by tapster on 2026-09-08T10:04:29.356017Z
class Journal < Formula
  desc "Automatic Git work log generator with AI analysis."
  homepage "https://github.com/CalsRanna/auto_reflect"
  if OS.mac?
    url "https://github.com/CalsRanna/auto_reflect/releases/download/v2.3.3/journal-macos"
    sha256 "f2fa71f21b742149081d604a86a0e3381ebca6d574746a1d1d37fde7f2bb5207"
  else
    url "https://github.com/CalsRanna/auto_reflect/releases/download/v2.3.3/journal-linux"
    sha256 "6e1db89d5c971dced6c2d55a7f1e6afdfc8df573d15242cc5a8e58616541be1a"
  end

  license "MIT"

  

  def install
    if OS.mac?
      bin.install "journal-macos" => "journal"
    else
      bin.install "journal-linux" => "journal"
    end

  end

  test do
    system "#{bin}/journal", "--version"
  end
end
