# Generated by tapster on 2026-08-13T08:15:25.284565Z
class Journal < Formula
  desc "Automatic Git work log generator with AI analysis."
  homepage "https://github.com/CalsRanna/auto_reflect"
  url "https://github.com/CalsRanna/auto_reflect/releases/download/v2.3.1/journal-macos"
  sha256 "6f7cd05afffaadce2d95df319a2fbef56f860c5c4725f613c4adb557b22adb00"
  license "MIT"

  

  def install
    bin.install "journal-macos" => "journal"
  end

  test do
    system "#{bin}/journal", "--version"
  end
end
