# Generated by tapster on 2026-09-08T07:48:56.659123Z
class Journal < Formula
  desc "Automatic Git work log generator with AI analysis."
  homepage "https://github.com/CalsRanna/auto_reflect"
  if OS.mac?
    url "https://github.com/CalsRanna/auto_reflect/releases/download/v2.3.2/journal-macos"
    sha256 "71974927ec85773f51176a7a5de2203c8653749b22d071f6bf054a670fcccead"
  else
    url "https://github.com/CalsRanna/auto_reflect/releases/download/v2.3.2/journal-linux"
    sha256 "85c748b176212f307d11203f60e02b0bb2dca106383f5bc95a091e62afca78ef"
  end

  license "MIT"

  

  def install
    if OS.mac?
      bin.install "journal-macos" => "journal"
    else
      bin.install "journal-linux" => "journal"
    end

  end

  test do
    system "#{bin}/journal", "--version"
  end
end
