# Generated by tapster on 2026-08-27T03:29:41.242420Z
class Tapster < Formula
  desc "A command-line tool for automating Homebrew/Scoop package publishing."
  homepage "https://github.com/CalsRanna/auto_pour"
  if OS.mac?
    url "https://github.com/CalsRanna/auto_pour/releases/download/v1.3.3/tapster-macos"
    sha256 "35f9454166f9e59c4c8db073b2b6cc409abcfa96993a36ed53f977b40b6ad36d"
  else
    url "https://github.com/CalsRanna/auto_pour/releases/download/v1.3.3/tapster-linux"
    sha256 "63bd32c8afcef0a9b2a2951959dfe01cf2c2d5fa1f48f83ece67bf0894101f1d"
  end

  license "MIT"

  depends_on "gh"

  def install
    if OS.mac?
      bin.install "tapster-macos" => "tapster"
    else
      bin.install "tapster-linux" => "tapster"
    end

  end

  test do
    system "#{bin}/tapster", "--version"
  end
end
