# Generated by tapster on 2026-08-13T08:32:13.768779Z
class Tapster < Formula
  desc "A command-line tool for automating Homebrew/Scoop package publishing."
  homepage "https://github.com/CalsRanna/auto_pour"
  url "https://github.com/CalsRanna/auto_pour/releases/download/v1.3.2/tapster-macos"
  sha256 "40c7383aa7448171afa0cdba64f8049a5c9f1c1764402ba8235d6ed59ea8ca64"

  license "MIT"

  depends_on "gh"

  def install
    bin.install "tapster-macos" => "tapster"

  end

  test do
    system "#{bin}/tapster", "--version"
  end
end
