# Generated by tapster on 2026-08-08T15:39:04.969785Z
class Tapster < Formula
  desc "A command-line tool for automating Homebrew/Scoop package publishing."
  homepage "https://github.com/CalsRanna/auto_pour"
  url "https://github.com/CalsRanna/auto_pour/releases/download/v1.2.0/tapster-macos"
  sha256 "370fadaca78d78c23a7fedba12bb685ba4d0c278a347b96861bf3db062aa1326"
  license "MIT"

  depends_on "gh"

  def install
    bin.install "tapster-macos" => "tapster"
  end

  test do
    system "#{bin}/tapster", "--version"
  end
end
